apiVersion: 1

contactPoints:
  - orgId: 1
    name: OTel PoC Local Webhook
    receivers:
      - uid: otel_poc_local_webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://alert-webhook-mock:8080/
          httpMethod: POST